services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_db
    ports:
      - "3306:3306"

  mvc-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
