version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8081"
  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"